config/routes.rb
TicketIt::Engine.routes.draw do
  root to:'tickets#index'

  resources :tickets do
    collection do
      get :dashboard
      get :kanban
    end
    member do
      get :public
    end
  end
  resources :comments
  resources :reporters
end

app/models/ticket_it/address.rb
module TicketIt
  class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
  end
end

app/models/ticket_it/application_record.rb
module TicketIt
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/ticket_it/attachment.rb
module TicketIt
  class Attachment < ApplicationRecord
    belongs_to :attachable, polymorphic: true
    has_attached_file :file
    do_not_validate_attachment_file_type :file
  end
end

app/models/ticket_it/comment.rb
module TicketIt
  class Comment < ApplicationRecord
    belongs_to :commenter, polymorphic: true
    belongs_to :commentable, polymorphic: true

    validates_presence_of :content, :commentable, :commenter

  end
end

app/models/ticket_it/reporter.rb
module TicketIt
  class Reporter < ApplicationRecord
    has_many :tickets, foreign_key: :ticket_it_reporter_id
    validates_uniqueness_of :email
  end
end

app/models/ticket_it/ticket.rb
module TicketIt
  class Ticket < ApplicationRecord
    belongs_to :resource, class_name: TicketIt.resource_class, optional: true
    has_secure_token :public_token
    has_many :comments, as: :commentable
    belongs_to :ticket_it_reporter, class_name: 'TicketIt::Reporter', optional: true
    validates_uniqueness_of :number, :public_token
    validates_presence_of :number, :name, :status
    accepts_nested_attributes_for :ticket_it_reporter
    has_many :attachments, class_name: 'TicketIt::Attachment', as: :attachable

    after_create_commit :ticket_created
    after_update_commit :ticket_updated

    def ticket_priorities
      TicketIt.ticket_priorities || %w(high critical blocker low)
    end

    def ticket_types
      TicketIt.ticket_types || []
    end

    def ticket_status
      TicketIt.ticket_status || %w(new work_in_progress quality_check closed)
    end

    def ticket_contact
      TicketIt.ticket_contact || %w(email phone)
    end

    def self.metrics_by_status
      statuses = {}
      statuses["all"] = Ticket.status_filters(nil).count
      (TicketIt.ticket_status || %w(new work_in_progress quality_check closed)).each do |status|
        statuses["#{status}"] = Ticket.status_filters(status).count
      end
      return statuses
    end

    scope :status_filters, -> (status) {
      if status
        where(status: status)
      else
        all
      end
    }

    private
    def ticket_created
      if self.ticket_it_reporter
        TicketsMailer.new_ticket(self).deliver_later
      end
    end

    def ticket_updated
      if self.ticket_it_reporter
        TicketsMailer.ticket_update(self).deliver_later
      end
    end

  end
end

app/controllers/ticket_it/application_controller.rb
module TicketIt
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    before_action :ensure_user, unless: :public_links

    def ensure_user
      unless ticketit_user
        redirect_to TicketIt.sign_in_url
      end
    end

    def public_links
      if (action_name == 'public') || (controller_name == 'comments' && action_name == 'create')
        true
      else
        false
      end
    end

  end
end

app/controllers/ticket_it/comments_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class CommentsController < ApplicationController

    def create
      @comment = Comment.new(comment_params)
      @comment.commenter = ticketit_user.present? ? ticketit_user : @comment.commentable.ticket_it_reporter
      respond_to do |format|
        if @comment.save
          @comment.commentable.update!(updated_at: Time.zone.now) if @comment.commenter != @comment.commentable.ticket_it_reporter
          format.html{redirect_back(fallback_location: polymorphic_url(@comment.commentable), notice: 'Commented!')}
          format.js{}
          format.json{render json: @comment.to_json}
        else
          format.html{redirect_back(fallback_location: polymorphic_url(@comment.commentable), notice: 'Failed to post a commented!')}
          format.js{}
          format.json{render json: @comment.to_json}
        end
      end
    end

    private
    def comment_params
      params.require(:comment).permit(:commenter_id, :commenter_type, :commentable_type, :commentable_id, :content)
    end

  end
end

app/controllers/ticket_it/reporters_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class ReportersController < ApplicationController

    def index
      @reporters = Reporter.all
    end

    def new
      @reporter = Reporter.new
    end

    def create
      @reporter = Reporter.new(reporter_params)
      respond_to do |format|
        if @reporter.save
          format.html{redirect_to @reporter, notice: 'Reporter enlisted successfully!'}
          format.js{}
          format.json {render @reporter.to_json, status: :created, location: @reporter}
        else
          format.html { render :new }
          format.js{}
          format.json { render json: @reporter.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
      @reporter = Reporter.left_joins(:tickets).find(params[:id])
    end

    def edit
      @reporter = Reporter.find(params[:id])
    end

    def update
      @reporter = Reporter.find(params[:id])
      respond_to do |format|
        if @reporter.update!(reporter_params)
          format.html{redirect_to @reporter, notice: 'Reporter updated successfully!'}
          format.js{}
          format.json {render @reporter.to_json, status: :updated, location: @reporter}
        else
          format.html { render :new }
          format.js{}
          format.json { render json: @reporter.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def reporter_params
      params.require(:reporter).permit(:name, :email, :phone, :organization, :position, :notes)
    end

  end
end

app/controllers/ticket_it/tickets_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class TicketsController < ApplicationController

    def index
      @all_tickets = Ticket.all.order(created_at: :desc)
      @tickets = Ticket.where(resource_id: ticketit_user.id).order(created_at: :desc)
    end

    def new
      @ticket = Ticket.new
    end

    def create
      @ticket = Ticket.new(ticket_params)
      @ticket.resource_id = ticketit_user.id
      respond_to do |format|
        if @ticket.save
          format.html{ redirect_to @ticket, notice:'New ticket created successfully!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.to_json}
        else
          format.html{ render :new, notice:'Failed to create a ticket!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.to_json}
        end
      end
    end

    def show
      @ticket = Ticket.left_joins(:comments).find(params[:id])
    end

    def public
      @ticket = Ticket.left_joins(:comments).find(params[:id])
    end

    def edit
      @ticket = Ticket.find(params[:id])
    end

    def update
      @ticket = Ticket.find(params[:id])
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html{ redirect_to @ticket, notice:'Ticket updated successfully!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{render json: @ticket.to_json}
          format.json{render json: @ticket.to_json, status: :created, location: @ticket}
        else
          format.html{ render :edit, notice:'Failed to update a ticket!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    def dashboard
      @ticket_metrics = Ticket.metrics_by_status
    end

    def kanban
      @tickets = Ticket.where(resource_id: ticketit_user.id).group_by { |t| t.status }
    end

    def destroy
      # This method is intentionally left empty because a good workflow is not to delete a ticket
      # but rather close it by commenting stale ticket on it.
    end

    private
    def ticket_params
      params.require(:ticket).permit(:number, :status, :name, :description, :resource_id, :ticket_type, :priority, :prefered_contact, :closed_at, :ticket_it_reporter_id)
    end

  end
end

app/helpers/ticket_it/application_helper.rb
module TicketIt
  module ApplicationHelper
  end
end

app/helpers/ticket_it/comments_helper.rb
module TicketIt
  module CommentsHelper
  end
end

app/helpers/ticket_it/reporters_helper.rb
module TicketIt
  module ReportersHelper
  end
end

app/helpers/ticket_it/tickets_helper.rb
module TicketIt
  module TicketsHelper
  end
end

app/views/ticket_it/tickets/_form.html.erb
<%= form_for ticket do |f| %>
    <% if !ticket.errors.empty? %>
        <ul>
          <% ticket.errors.full_messages.each do |m| %>
              <li><%= m %></li>
          <% end %>
        </ul>
    <% end %>
    <div class="field">
      <%= f.label :number %>
      <br/>
      <%= f.text_field :number %>
    </div>
    <div class="field">
      <%= f.label :status %>
      <br/>
      <%= f.select :status, @ticket.ticket_status.map {|t| [t.humanize, t]} %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :priority %>
      <br/>
      <%= f.select :priority, @ticket.ticket_priorities.map {|t| [t.humanize, t]}, {prompt: true} %>
    </div>
    <div class="field">
      <%= f.label :ticket_type %>
      <br/>
      <%= f.select :ticket_type, @ticket.ticket_types.map {|t| [t.humanize, t]}, {prompt: true} %>
    </div>
    <div class="field">
      <%= f.label :prefered_contact %>
      <br/>
      <%= f.select :prefered_contact, @ticket.ticket_contact.map {|t| [t.humanize, t]}, {prompt: true} %>
    </div>
    <div class="actions">
      <%= f.submit "#{ticket.persisted? ? 'Update Ticket' : 'Save Ticket'}" %>
      <%= link_to 'Cancel', tickets_path %>
    </div>
<% end %>

app/views/ticket_it/tickets/dashboard.html.erb
<h1>Dashboard</h1>
<!--Sample of metrics {"all"=>1, "new"=>1, "work_in_progress"=>0, "quality_check"=>0, "closed"=>0}-->
<% @ticket_metrics.each do |m,v| %>
    <p><strong><%= m.to_s.humanize %>: </strong><%= v %></p>
<% end %>

app/views/ticket_it/tickets/edit.html.erb
<h2>Edit ticket</h2>
<%= render partial: 'form', locals: {ticket: @ticket}%>

app/views/ticket_it/tickets/index.html.erb
<h1><%= params[:filter]=='all_tickets' ? 'All Tickets' : 'My Tickets' %></h1>
<%= link_to 'New', new_ticket_path %>
<br/>
<strong>Filters:</strong><br>
<%= link_to 'My Tickets', tickets_path(filter: :my_tickets) %>
<%= link_to 'All Tickets', tickets_path(filter: :all_tickets) %>
<table>
  <thead>
  <tr>
    <th>Number</th>
    <th>Name</th>
    <th>Priority</th>
    <th>Status</th>
    <th>Type</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% tickets = params[:filter]=='all_tickets' ? @all_tickets : @tickets %>
  <% tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.number %></td>
    <td><%= link_to ticket.name, ticket_path(ticket) %></td>
    <td><%= ticket.priority.humanize %></td>
    <td><%= ticket.status.humanize %></td>
    <td><%= ticket.ticket_type.humanize %></td>
    <td>
      <%= link_to 'Edit', edit_ticket_path(ticket) %> |
      <%= link_to 'Delete', ticket_path(ticket), method: :delete, data:{confirm:'Are you sure?'} %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/ticket_it/tickets/kanban.html.erb
<h1>Kanban Board</h1>
<% TicketIt::Ticket.first.ticket_status.each do |s| %>
    <div>
      <h3><%= s.humanize %></h3>
      <ul>
        <% if @tickets["#{s}"] %>
            <% @tickets["#{s}"].each do |t| %>
                <li><%= link_to t.name, tickets_path(t) %></li>
            <% end %>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/ticket_it/tickets/new.html.erb
<h2>Create a ticket</h2>
<%= render partial: 'form', locals: {ticket: @ticket}%>

app/views/ticket_it/tickets/public.html.erb
<h1><%= @ticket.name %></h1>
<p><strong>Number:</strong><br><%= @ticket.number %></p>
<p><strong>Status:</strong><br><%= @ticket.status %></p>
<p><strong>Name:</strong><br><%= @ticket.name %></p>
<!--In case if using a text editor for ticket description.-->
<p><strong>Description:</strong><br><%= raw @ticket.description %></p>
<p><strong>Priority:</strong><br><%= @ticket.priority.humanize %></p>
<p><strong>Ticket Type:</strong><br><%= @ticket.ticket_type %></p>
<p><strong>Leave a Comment</strong></p>
<%= form_for @ticket.comments.new do |f| %>
  <%= f.hidden_field :commentable_id, value: @ticket.id %>
  <%= f.hidden_field :commentable_type, value: @ticket.class %>
  <%= f.text_area :content %>
  <%= f.submit 'Comment' %>
<% end %>
<p><strong>Comments</strong></p>
<%= render @ticket.comments.order(created_at: :desc) %>

app/views/ticket_it/tickets/show.html.erb
<h1><%= @ticket.name %></h1>
<p><strong>Number:</strong><br><%= @ticket.number %></p>
<p><strong>Status:</strong><br><%= @ticket.status %></p>
<p><strong>Name:</strong><br><%= @ticket.name %></p>
<!--In case if using a text editor for ticket description.-->
<p><strong>Description:</strong><br><%= raw @ticket.description %></p>
<p><strong>Priority:</strong><br><%= @ticket.priority.humanize %></p>
<p><strong>Ticket Type:</strong><br><%= @ticket.ticket_type %></p>
<p><strong>Leave a Comment</strong></p>
<%= form_for @ticket.comments.new do |f| %>
    <%= f.hidden_field :commentable_id, value: @ticket.id %>
    <%= f.hidden_field :commentable_type, value: @ticket.class %>
    <%= f.text_area :content %>
    <%= f.submit 'Comment' %>
<% end %>
<p><strong>Comments</strong></p>
<%= render @ticket.comments.order(created_at: :desc) %>