config/routes.rb
TicketIt::Engine.routes.draw do
  root to:'tickets#index'

  resources :tickets do
    collection do
      get :dashboard
      get :kanban
    end
    member do
      get :public
    end
  end
  resources :comments
  resources :reporters
end

app/models/ticket_it/address.rb
module TicketIt
  class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
  end
end

app/models/ticket_it/application_record.rb
module TicketIt
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/ticket_it/attachment.rb
module TicketIt
  class Attachment < ApplicationRecord
    belongs_to :attachable, polymorphic: true
    has_attached_file :file
    do_not_validate_attachment_file_type :file
  end
end

app/models/ticket_it/comment.rb
module TicketIt
  class Comment < ApplicationRecord
    belongs_to :commenter, polymorphic: true
    belongs_to :commentable, polymorphic: true

    validates_presence_of :content, :commentable, :commenter

  end
end

app/models/ticket_it/reporter.rb
module TicketIt
  class Reporter < ApplicationRecord
    has_many :tickets, foreign_key: :ticket_it_reporter_id
    validates_uniqueness_of :email
  end
end

app/models/ticket_it/ticket.rb
module TicketIt
  class Ticket < ApplicationRecord
    belongs_to :resource, class_name: TicketIt.resource_class, optional: true
    has_secure_token :public_token
    has_many :comments, as: :commentable
    belongs_to :ticket_it_reporter, class_name: 'TicketIt::Reporter', optional: true
    validates_uniqueness_of :number, :public_token
    validates_presence_of :number, :name, :status
    accepts_nested_attributes_for :ticket_it_reporter
    has_many :attachments, class_name: 'TicketIt::Attachment', as: :attachable

    after_create_commit :ticket_created
    after_update_commit :ticket_updated

    def ticket_priorities
      TicketIt.ticket_priorities || %w(high critical blocker low)
    end

    def ticket_types
      TicketIt.ticket_types || []
    end

    def ticket_status
      TicketIt.ticket_status || %w(new work_in_progress quality_check closed)
    end

    def ticket_contact
      TicketIt.ticket_contact || %w(email phone)
    end

    def self.metrics_by_status
      statuses = {}
      statuses["all"] = Ticket.status_filters(nil).count
      (TicketIt.ticket_status || %w(new work_in_progress quality_check closed)).each do |status|
        statuses["#{status}"] = Ticket.status_filters(status).count
      end
      return statuses
    end

    scope :status_filters, -> (status) {
      if status
        where(status: status)
      else
        all
      end
    }

    private
    def ticket_created
      if self.ticket_it_reporter
        TicketsMailer.new_ticket(self).deliver_later
      end
    end

    def ticket_updated
      if self.ticket_it_reporter
        TicketsMailer.ticket_update(self).deliver_later
      end
    end

  end
end

app/controllers/ticket_it/application_controller.rb
module TicketIt
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    before_action :ensure_user, unless: :public_links

    def ensure_user
      unless ticketit_user
        redirect_to TicketIt.sign_in_url
      end
    end

    def public_links
      if (action_name == 'public') || (controller_name == 'comments' && action_name == 'create')
        true
      else
        false
      end
    end

  end
end

app/controllers/ticket_it/comments_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class CommentsController < ApplicationController

    def create
      @comment = Comment.new(comment_params)
      @comment.commenter = ticketit_user.present? ? ticketit_user : @comment.commentable.ticket_it_reporter
      respond_to do |format|
        if @comment.save
          @comment.commentable.update!(updated_at: Time.zone.now) if @comment.commenter != @comment.commentable.ticket_it_reporter
          format.html{redirect_back(fallback_location: polymorphic_url(@comment.commentable), notice: 'Commented!')}
          format.js{}
          format.json{render json: @comment.to_json}
        else
          format.html{redirect_back(fallback_location: polymorphic_url(@comment.commentable), notice: 'Failed to post a commented!')}
          format.js{}
          format.json{render json: @comment.to_json}
        end
      end
    end

    private
    def comment_params
      params.require(:comment).permit(:commenter_id, :commenter_type, :commentable_type, :commentable_id, :content)
    end

  end
end

app/controllers/ticket_it/reporters_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class ReportersController < ApplicationController

    def index
      @reporters = Reporter.all
    end

    def new
      @reporter = Reporter.new
    end

    def create
      @reporter = Reporter.new(reporter_params)
      respond_to do |format|
        if @reporter.save
          format.html{redirect_to @reporter, notice: 'Reporter enlisted successfully!'}
          format.js{}
          format.json {render @reporter.to_json, status: :created, location: @reporter}
        else
          format.html { render :new }
          format.js{}
          format.json { render json: @reporter.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
      @reporter = Reporter.left_joins(:tickets).find(params[:id])
    end

    def edit
      @reporter = Reporter.find(params[:id])
    end

    def update
      @reporter = Reporter.find(params[:id])
      respond_to do |format|
        if @reporter.update!(reporter_params)
          format.html{redirect_to @reporter, notice: 'Reporter updated successfully!'}
          format.js{}
          format.json {render @reporter.to_json, status: :updated, location: @reporter}
        else
          format.html { render :new }
          format.js{}
          format.json { render json: @reporter.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def reporter_params
      params.require(:reporter).permit(:name, :email, :phone, :organization, :position, :notes)
    end

  end
end

app/controllers/ticket_it/tickets_controller.rb
require_dependency "ticket_it/application_controller"

module TicketIt
  class TicketsController < ApplicationController

    def index
      @all_tickets = Ticket.all.order(created_at: :desc)
      @tickets = Ticket.where(resource_id: ticketit_user.id).order(created_at: :desc)
    end

    def new
      @ticket = Ticket.new
    end

    def create
      @ticket = Ticket.new(ticket_params)
      @ticket.resource_id = ticketit_user.id
      respond_to do |format|
        if @ticket.save
          format.html{ redirect_to @ticket, notice:'New ticket created successfully!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.to_json}
        else
          format.html{ render :new, notice:'Failed to create a ticket!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.to_json}
        end
      end
    end

    def show
      @ticket = Ticket.left_joins(:comments).find(params[:id])
    end

    def public
      @ticket = Ticket.left_joins(:comments).find(params[:id])
    end

    def edit
      @ticket = Ticket.find(params[:id])
    end

    def update
      @ticket = Ticket.find(params[:id])
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html{ redirect_to @ticket, notice:'Ticket updated successfully!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{render json: @ticket.to_json}
          format.json{render json: @ticket.to_json, status: :created, location: @ticket}
        else
          format.html{ render :edit, notice:'Failed to update a ticket!'}
          #to use js reponse please create a response file at app/views/ticket_it/tickets/create.js.erb
          format.js{}
          format.json{render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    def dashboard
      @ticket_metrics = Ticket.metrics_by_status
    end

    def kanban
      @tickets = Ticket.where(resource_id: ticketit_user.id).group_by { |t| t.status }
    end

    def destroy
      # This method is intentionally left empty because a good workflow is not to delete a ticket
      # but rather close it by commenting stale ticket on it.
    end

    private
    def ticket_params
      params.require(:ticket).permit(:number, :status, :name, :description, :resource_id, :ticket_type, :priority, :prefered_contact, :closed_at, :ticket_it_reporter_id)
    end

  end
end

app/helpers/ticket_it/application_helper.rb
module TicketIt
  module ApplicationHelper
  end
end

app/helpers/ticket_it/comments_helper.rb
module TicketIt
  module CommentsHelper
  end
end

app/helpers/ticket_it/reporters_helper.rb
module TicketIt
  module ReportersHelper
  end
end

app/helpers/ticket_it/tickets_helper.rb
module TicketIt
  module TicketsHelper
  end
end

app/views/ticket_it/reporters/_form.html.erb
<%= form_for reporter do |f| %>
    <% if !reporter.errors.empty? %>
        <ul>
          <% reporter.errors.full_messages.each do |m| %>
              <li><%= m %></li>
          <% end %>
        </ul>
    <% end %>
    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <br/>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :phone %>
      <br/>
      <%= f.phone_field :phone %>
    </div>
    <div class="field">
      <%= f.label :organization %>
      <br/>
      <%= f.text_field :organization %>
    </div>
    <div class="field">
      <%= f.label :position %>
      <br/>
      <%= f.text_field :position %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <br/>
      <%= f.text_area :notes %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "#{reporter.persisted? ? 'Update Reporter' : 'Save Reporter'}" %>
      <%= link_to 'Cancel', reporters_path %>
    </div>
<% end %>

app/views/ticket_it/reporters/edit.html.erb
<h2>Update a Reporter</h2>
<%= render partial: 'form', locals: {reporter: @reporter}%>

app/views/ticket_it/reporters/index.html.erb
<h1>All Reporters</h1>
<%= link_to 'New', new_reporter_path %>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Position</th>
  </tr>
  </thead>
  <tbody>
  <% if !@reporters.empty? %>
      <% @reporters.each do |reporter| %>
          <tr>
            <td><%= link_to reporter.name, reporter_path(reporter) %></td>
            <td><%= reporter.email %></td>
            <td><%= reporter.position %></td>
          </tr>
      <% end %>
  <% else %>
    <tr>
      <td colspan="3"> No reporters yet!</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/ticket_it/reporters/new.html.erb
<h2>Create a Reporter</h2>
<%= render partial: 'form', locals: {reporter: @reporter}%>

app/views/ticket_it/reporters/show.html.erb
<h1><%= @reporter.name %></h1>
<div>
  <p><strong>Name:</strong><%= @reporter.name %></p>
  <p><strong>Email:</strong><%= @reporter.email %></p>
  <p><strong>Phone:</strong><%= @reporter.phone %></p>
  <p><strong>Organization:</strong><%= @reporter.organization %></p>
  <p><strong>Position:</strong><%= @reporter.position %></p>
  <p><strong>Notes:</strong><%= raw @reporter.notes %></p>
</div>
<%= link_to 'Edit', edit_reporter_path(@reporter) %>

<h2>Tickets</h2>
<hr>
<div>
  <ul>
    <% @reporter.tickets.each do |t| %>
    <li><%= link_to t.name, ticket_path(t) %></li>
    <% end %>
  </ul>
</div>